---
title: "Home"
site: workflowr::wflow_site
author: Jiayuan Zhu
output:
  html_document:
    toc: TRUE

---

This research website is maintained for the documentation of the project "Identification of translational regulation elements in mRNA" under the supervision of [Heejung Shim](https://heejungshim.org).

***

# Abstract
In contrast to our knowledge of transcriptional regulation, much less is known about translational regulation. A particularly intriguing model of translational regulation involves upstream open reading frames (uORFs). This project develops a statistical model to identify the locations of translated uORFs and main coding regions within the messenger RNA (mRNA). It would further facilitate systematic investigations of uORFs regulator functions.

After studying the characteristics of ribosome profiling data, a hidden Markov model (HMM) is developed for the comprehensive identification of uORFs and main coding regions within the mRNA. Then it is implemented in Python. The estimation of model parameters involves the Expectation-Maximization (EM) algorithm. Identification of the locations of translated regions is conducted by the Viterbi algorithm. Besides, simulation datasets are constructed to verify model correctness.

# Project description
This project is part of large project Identification of translational regulatory elements.

It is an extension of previous work [Thousands of novel translated open reading frames in humans inferred by ribosome footprint profiling](assets/Previous work.pdf) and Jiangrong's work. 

The major difference in my project is to allow transitional initial occur at non-canonical start codon. It provides more flexibility and is more similar to current biology assumption.


# Derivation
In this document [Derivation with 21 states](assets/Derivation Full.pdf), math derivation was based on 21 hidden states. Second part's (p11-p17) derivation was applied with logistic. However, in the real computation, some constrain issues / assumption conflicts occured so it was disgraded for implementation. 

This file [Derivation with 10 states](assets/Derivation with 10 states.pdf) was a simplied version that several states were merged to reduce implementation complexity. Computation results for this two versions would be compared later.

# Poster
The poster session was conducted on 12/2/2021 for Maths & Stats Vaction Sholarship program hold by the Unversity of Melbourne. Here's my [Poster](assets/Poster.pdf).

# Presentation slides
The [Presentation](assets/Presentation.pdf) was conducted on 4/6/2021 for Research Project. Thanks to Jiangrong Ouyang for sharing his slides. Some of my slides and figures are modification of him.

# Report
Here's the report with both 21 and 10 hidden states. Results and anslysis were based on simulation data. Appendix included derivation details and algorithm to simulate data. 
As its an ongoing project, so if you are interested in it, please contact me first and then I can provide some further information.

# Codes
EM algorithm for updating parameters: [orfHMM_EM](assets/orfHMM_EM.py)

Viterbi algorithm for backtracking hidden states: [orfHMM_Viterbi](assets/orfHMM_Viterbi.py)

# Simulation Tests
[Simulation for 21 states with 1 start codon](assets/Simulation for 21 states with 1 start codon.html)

[Simulation for 21 states with 3 start codons](assets/Simulation for 21 states with 3 start codons.html)

10 hidden states: update later

# Software Page
Here's the [link](https://github.com/shimlab/orfHMM) for software.

# Resources
[Christopher M. Bishop (2006) -- Pattern Recognition and Machine Learning -- Chapter 13](assets/Christopher M. Bishop.pdf)

[Jia Li's slides](assets/Jia Li's slides.pdf)

[Marcin Marszalek's slides (2009)](assets/Marcin Marszalek's slides.pdf)

[Mark Stamp (2021) -- A Revealing Introduction to Hidden Markov Models](assets/Mark Stamp.pdf)

[A quick video on Hidden Markov Models](https://www.youtube.com/watch?v=4XqWadvEj2k&list=PLpAeikDnrZLU_hmWcY00EXuV3z8unmUfQ&index=4)

[A quick video on Markov Models](https://www.youtube.com/watch?v=4XqWadvEj2k&list=PLpAeikDnrZLU_hmWcY00EXuV3z8unmUfQ&index=5)

